enzymes=struct();
enzymes.name={'atpsac';...
     
     
    'fbpase';...
    'fbpasen';...
    'sbpase';...
    'sbpasen';...
    'prk';...
    'prkn';...
     

    'vdeh3';...
    'psbsh6zx';...
    'stn7a';...
    'pph1a'};

enzymes.EC={'3.6.3.14';...
     
     
    '3.1.3.11';...
    '3.1.3.11';...
    '3.1.3.37';...
    '3.1.3.37';...
    '2.7.1.19';...
    '2.7.1.19';...
     
    '1.14.15.21';...
    '';...
    '2.7.11.1';...
    '3.1.3.16'};
enzymes.noncata={'P680';'P680e';'pheo';'pheon';'P680p';'QA';'QAn';'QB';'QBn';'QBn2';'s0';'s0p';'s1';'s1p';'s2';'s2p';'s3';'s3p';'s4';'s4p';...
    'ISPox';'ISPoxPQH2';'PQsemi';'ISPHred';'cytf';'cytfn';'ISPHp';'cytbl';'cytbln';'cytbh';'cytbhn';'P700';'P700e';'A0';'A0n';'P700p';...
    'atps';'Rcai';'Rcaa';'ER';'ERRcaa';'ERcaa';'E';'ECR';'ECRRcaa';'ECRcaa';'EC';'ECM';'ECMR';'ECMRC';'RPGA2H';'RPGA2';'RPGA';...
    'ECMRO2';'PGAPGLRubiH2';'PGAPGLRubi';'PGAPGL'; 'psbs';'psbsh6';'VDE';'stn7';'pph1';'chl2_m';'chl2_me';'chl1_m';'chl1_me';'chl2_p';'chl2_pe';'chl1_p';'chl1_pe';...
    'chl2_c';'chl2_ce';'chl1_c';'chl1_ce'};

% 1: oxidoreductase
% 2: Transferase
% 3: Hydrolase: hydrolytic cleavage
% 4: Lyases: remove bonds(aldolase, decarboxylase)
% 5: Isomerase: geometric or structural changes in 1 molecule
% 6: synthase: catalyze the junction of 2 molecules
% 7: translocase: movement of ions or molecules across membrane
